package com.amazonas.backend.business.permissions.actions;

public enum MarketActions {

    // general actions
    CREATE_STORE,
    SEARCH_PRODUCTS,
    MAKE_PURCHASE,
    SHUTDOWN_MARKET,
    RESTART,

    // shipping management
    ADD_SHIPPING_SERVICE,
    REMOVE_SHIPPING_SERVICE,
    UPDATE_SHIPPING_SERVICE,
    ENABLE_SHIPPING_SERVICE,
    DISABLE_SHIPPING_SERVICE,

    // payment management
    ADD_PAYMENT_SERVICE,
    REMOVE_PAYMENT_SERVICE,
    UPDATE_PAYMENT_SERVICE,
    DISABLE_PAYMENT_SERVICE,
    ENABLE_PAYMENT_SERVICE,

    ADD_PAYMENT_METHOD,
    REMOVE_PAYMENT_METHOD,
    UPDATE_PAYMENT_METHOD,
    ENABLE_PAYMENT_METHOD,
    DISABLE_PAYMENT_METHOD, START_MARKET,

}
