package com.amazonas.business.permissions.actions;

public enum UserActions {

    VIEW_SHOPPING_CART,
    ADD_TO_SHOPPING_CART,
    REMOVE_FROM_SHOPPING_CART,
    UPDATE_SHOPPING_CART,
    REGISTER,
    LOGIN,
    LOGOUT,
    VIEW_PROFILE,
    VIEW_USER_TRANSACTIONS, START_PURCHASE, PAY_FOR_PURCHASE, CANCEL_PURCHASE,
}
